export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const OPEN_MODAL_CONFIRM = 'OPEN_MODAL_CONFIRM';
export const CLOSE_MODAL_CONFIRM = 'CLOSE_MODAL_CONFIRM';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_TRIP_BEGIN = 'CREATE_TRIP_BEGIN';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_ERROR = 'CREATE_TRIP_ERROR';

export const GET_TRIPS_BEGIN = 'GET_TRIPS_BEGIN';
export const GET_USER_TRIPS_SUCCESS = 'GET_USER_TRIPS_SUCCESS';
export const GET_ALL_TRIPS_SUCCESS = 'GET_ALL_TRIPS_SUCCESS';
export const GET_SINGLE_TRIP_SUCCESS = 'GET_SINGLE_TRIP_SUCCESS';
export const GET_TRIPS_ERROR = 'GET_TRIPS_ERROR';

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN';

export const DELETE_TRIP_BEGIN = 'DELETE_TRIP_BEGIN';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const CLEAR_TRIP_FORM = 'CLEAR_TRIP_FORM';
